@startuml

title __CONTROLLER's Class Diagram__\n

package ca.ualberta.CMPUT3012019T02.alexandria {

    package ca.ualberta.CMPUT3012019T02.alexandria.controller {

        class AuthenticationController {
            - auth : FirebaseAuth
            {static} - instance : AuthenticationController
            - AuthenticationController()
            {static} + getInstance() : AuthenticationController
            + authenticate(String username, String password) : boolean
            + deauthenticate() : void
            + createUser(String username, String password) : boolean
            + getMyId() : String
        }
        note top: "Used for keeping track of authentication\ndata and communicate authentication\ninformation with firebase"

        class BookController {
            - database : FirebaseDatabase
            {static} - instance : BookController
            - BookController()
            {static} + getInstance() : BookController
            + getBook(String isbn) : Book
            + getMyBorrowedBooks() : ArrayList<Book>
            + getMyOwnedBooks() : ArrayList<Book>
            + getOwnedBooks(String id) : ArrayList<Book>
            + updateMyBorrowedBooks(Book book) : void
            + updateMyOwnedBooks(Book book) : void
            + updateBook(String isbn, Book newBook) : void
        }
        note top: "Used for keeping track of book transaction\ndata and communicate book transaction\ninformation with firebase"

        class UserProfileController {
             - database : FirebaseDatabase
            {static} - instance : UserProfileController
            - UserProfileController()
            {static} + getInstance() : UserProfileController
            + getUserProfile(String id) : UserProfile
            + getMyProfile() : UserProfile
            + updateMyProfile(UserProfile userProfile) : void
        }
        note top: "Used for keeping track of user profile\ndata and communicate user profile\ninformation with firebase"

        class ChatController {
            - database : FirebaseDatabase
            {static} - instance : ChatController
            - ChatController()
            {static} + getInstance() : ChatController
            + getChatRoom(String id) : ChatRoom 
            + updateMessages() : ChatRoom 
            + postMessage(Message message) : void
        }
        note top: "Used for keeping track of chat\ndata and communicate chat\ninformation with firebase"

    }


    package ca.ualberta.CMPUT3012019T02.alexandria.model {

        class BorrowedBook { 
            See MODEL's class diagram
        }

        class OwnedBook { 
            See MODEL's class diagram
        }

        class Book { 
            See MODEL's class diagram
        }

        class User { 
            See MODEL's class diagram
        }

        class UserProfile { 
            See MODEL's class diagram
        }

        class ChatRoom { 
            See MODEL's class diagram
        }

        class Message { 
            See MODEL's class diagram
        }

    }

}

AuthenticationController "1" -down- "*" User : manages >

UserProfileController "1" -down- "*" UserProfile : manages >
UserProfileController "1" -up- "1" AuthenticationController : interfaces with >

BookController "1" -down- "*" BorrowedBook : manages >
BookController "1" -down- "*" OwnedBook : manages >
BookController "1" -down- "*" Book : manages >
BookController "1" -right- "1" AuthenticationController : interfaces with >

ChatController "1" -down- "*" ChatRoom : manages >
ChatController "1" -down- "*" Message : manages >
ChatController "1" -left- "1" AuthenticationController : interfaces with >

@enduml