@startuml

title __MODEL's Class Diagram__\n

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class Book {
          - isbn : String
          - imageId : String
          - title : String
          - author : String
          - description : String
          - date : Date
          - availableOwners : List<String>
          + Book()
          + Book()
          + getIsbn()
          + setIsbn()
          + getImageId()
          + setImageId()
          + getTitle()
          + setTitle()
          + getAuthor()
          + setAuthor()
          + getDate()
          + setDate()
          + getAvailableOwners()
          + setAvailableOwners()
          + addAvailableOwners()
          + removeAvailableOwners()
          + getDescription()
          + setDescription()
          + equals()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class BookList {
          - cover : Bitmap
          - title : String
          - author : String
          - isbn : String
          - status : String
          - owner : String
          + BookList()
          + BookList()
          + getCover()
          + setCover()
          + getTitle()
          + setTitle()
          + getAuthor()
          + setAuthor()
          + getIsbn()
          + setIsbn()
          + getStatus()
          + setStatus()
          + getOwner()
          + setOwner()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class BookRecyclerViewAdapter {
          - mContext : Context
          - mBookListItem : List<BookList>
          - destination : String
          + BookRecyclerViewAdapter()
          + onCreateViewHolder()
          + onBindViewHolder()
          + getItemCount()
          - dataBundler()
          + setmBookList()
          - setDestination()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class BookViewHolder {
          + itemBook : LinearLayout
          + ivCover : ImageView
          + tvTitle : TextView
          + tvAuthor : TextView
          + tvISBN : TextView
          + ivStatus : ImageView
          + BookViewHolder()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class ChatRecyclerViewAdapter {
          - mContext : Context
          - mChatRoomList : List<ChatRoomItem>
          + ChatRecyclerViewAdapter()
          + onCreateViewHolder()
          + onBindViewHolder()
          + getItemCount()
          + updateChatRoomList()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class ChatRoom {
          - messages : List<Message>
          - id : String
          + ChatRoom()
          + getMessages()
          + setMessages()
          + addMessage()
          + removeMessage()
          + getId()
          + setId()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class ChatRoomItem {
          - user1Id : String
          - user1Name : String
          - user2Id : String
          - user2Name : String
          - chatId : String
          - readStatus : boolean
          + ChatRoomItem()
          + ChatRoomItem()
          + toMap()
          + getUser1Id()
          + setUser1Id()
          + getUser1Name()
          + setUser1Name()
          + getUser2Id()
          + setUser2Id()
          + getUser2Name()
          + setUser2Name()
          + getChatId()
          + setChatId()
          + getReadStatus()
          + setReadStatus()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class ChatViewHolder {
          + itemChat : LinearLayout
          + tvChatRecieverUsername : TextView
          + ivChatUserPic : ImageView
          + ivReadStatus : ImageView
          + ChatViewHolder()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class Location {
          - latitude : double
          - longitude : double
          + Location()
          + getLatitude()
          + setLatitude()
          + getLongitude()
          + setLongitude()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class MessageRecyclerViewAdapter {
          - mContext : Context
          - mMessageList : List<Message>
          + MessageRecyclerViewAdapter()
          + onCreateViewHolder()
          + onBindViewHolder()
          + getItemCount()
          + updateMessageList()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class MessageViewHolder {
          + itemMessage : LinearLayout
          + tvContent : TextView
          + tvSenderUsername : TextView
          + MessageViewHolder()
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      class TabsAdapter {
          - mFragmentList : List<Fragment>
          - mFragmentTitleList : List<String>
          + TabsAdapter()
          + addFragment()
          + getPageTitle()
          + getItem()
          + getCount()
      }
    }
  }
  
  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.message {
        class ImageMessage {
            + ImageMessage()
            + getImage()
            + setImage()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.message {
        class LocationMessage {
            + LocationMessage()
            + getLocation()
            + setLocation()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.message {
        abstract class Message {
            - id : String
            - type : String
            - content : String
            - status : String
            - date : String
            - sender : String
            + Message()
            + Message()
            + toMap()
            + getId()
            + setId()
            + getType()
            + setType()
            + getContent()
            + setContent()
            + getStatus()
            + setStatus()
            + getDate()
            + setDate()
            + getSender()
            + setSender()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.message {
        class TextMessage {
            + TextMessage()
            + TextMessage()
            + getText()
            + setText()
        }
      }
    }
  }
  
  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.user {
        class BorrowedBook {
            + BorrowedBook()
            + BorrowedBook()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.user {
        class OwnedBook {
            - usersRequesting : List<String>
            - images : List<String>
            - userBorrowing : String
            + OwnedBook()
            + OwnedBook()
            + OwnedBook()
            + getUsersRequesting()
            + setUsersRequesting()
            + addUserRequesting()
            + removeUserRequesting()
            + getImages()
            + setImages()
            + addImage()
            + removeImage()
            + getUserBorrowing()
            + setUserBorrowing()
        }
      }
    }
  }

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.user {
        class User {
            - chatRooms : Map<String, String>
            - ownedBooks : HashMap<String, OwnedBook>
            - borrowedBooks : HashMap<String, BorrowedBook>
            - id : String
            - blockedUsers : List<String>
            + User()
            + getChatRooms()
            + setChatRooms()
            + addChatRoom()
            + removeChatRoom()
            + getOwnedBooks()
            + setOwnedBooks()
            + addOwnedBook()
            + removeOwnedBook()
            + getBorrowedBooks()
            + setBorrowedBooks()
            + addBorrowedBook()
            + removeBorrowedBook()
            + getProfile()
            + setProfile()
            + getId()
            + setId()
            + getBlockedUsers()
            + setBlockedUsers()
            + addBlockedUser()
            + removeBlockedUser()
            + isBlockedUser()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.user {
        abstract class UserBook {
            - isbn : String
            - status : String
            - owner : String
            ~ UserBook()
            + getIsbn()
            + setIsbn()
            + getStatus()
            + setStatus()
            + getOwner()
            + setOwner()
        }
      }
    }
  }
  

  package ca.ualberta.CMPUT3012019T02.alexandria {
    package ca.ualberta.CMPUT3012019T02.alexandria.model {
      package ca.ualberta.CMPUT3012019T02.alexandria.model.user {
        class UserProfile {
            - name : String
            - email : String
            - phone : String
            - picture : String
            - username : String
            + UserProfile()
            + UserProfile()
            + getName()
            + setName()
            + getEmail()
            + setEmail()
            + getPhone()
            + setPhone()
            + getPicture()
            + setPicture()
            + getUsername()
            + setUsername()
        }
      }
    }
  }
  

  BorrowedBook -up-|> UserBook
  OwnedBook -up-|> UserBook

  User "1" o-up- "1" UserProfile
  User "1" o-down- "*" OwnedBook
  User "1" o-down- "*" BorrowedBook
  User "2" -left- "*" ChatRoom : participates in >
  User "*" o-right- "*" User : blocked >

  OwnedBook "*" -- "1" User : borrowed by >
  OwnedBook "*" -- "*" User : requested by >
  OwnedBook "*" -down- "1" Book : references >

  BorrowedBook "*" -- "1" User : owned by >
  BorrowedBook "*" -down- "1" Book : references >

  Book "*" -up- "*" User : available from >

  ChatRoom "1" *-down- "*" Message

  ImageMessage -up-|> Message

  LocationMessage -up-|> Message
  LocationMessage "1" o-- "1" Location

  TextMessage -up-|> Message

  Message "*" -right- "1" User : sent by >

  BookRecyclerViewAdapter -up-|> Adapter
  BookViewHolder -up-|> ViewHolder
  ChatRecyclerViewAdapter -up-|> Adapter
  ChatViewHolder -up-|> ViewHolder
  MessageRecyclerViewAdapter -up-|> Adapter
  MessageViewHolder -up-|> ViewHolder
  TabsAdapter -up-|> FragmentPagerAdapter

  BookList "*" -- "1" Book
  BookList "*" -- "1" UserBook

right footer


PlantUML diagram partly generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
